import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Old Goat - Tattoo UK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.logoContainer}>
            <Image
              className={styles.logo}
              src="/next.svg"
              alt="Next.js Logo"
              width={2160}
              height={444}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://www.instagram.com/oldgoattattoo/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              className={styles.logo}
              src="/instagram.svg"
              alt="Instagram Logo"
              width={30}
              height={30}
              priority
            />
            <h2 className={inter.className}>
              Instagram <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Check out my Instagram for more tattoo designs!
            </p>
          </a>

          <a
            href="https://www.linkedin.com/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              className={styles.logo}
              src="/linkedin.svg"
              alt="LinkedIn Logo"
              width={30}
              height={30}
              priority
            />
            <h2 className={inter.className}>
              LinkedIn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Connect with me on LinkedIn for professional inquiries.
            </p>
          </a>

          <a
            href="https://www.youtube.com/@jvshake"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              className={styles.logo}
              src="/youtube.svg"
              alt="YouTube Logo"
              width={30}
              height={30}
              priority
            />
            <h2 className={inter.className}>
              YouTube <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Subscribe to my YouTube channel for tattoo tutorials!
            </p>
          </a>

          <a
            href="http://wa.me/SG4KE31B7FNGO1"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              className={styles.logo}
              src="/whatsapp.svg"
              alt="WhatsApp Logo"
              width={30}
              height={30}
              priority
            />
            <h2 className={inter.className}>
            WhatsApp <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Message me on WhatsApp to book an appointment!
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
